### ISSUE TITLE
refactor:jsonNodeTrxImpl.JsonNodeTrx

### ISSUE THREAD

**Issue by mikkar2** [soffan20/sirix#10]
Original complexity using Code Smell Detector: 28

**Comment by JohannesLichtenberger** [comment]
That's on my agenda for some time now... even worse: XmlNodeTrx.

Idea: Splitting according to Insert/Delete/Update operations and Hashes. For instance the insert-operations should then just delegate to insertionCommand.insertAsFirstChild(...) or something like that.
