### ISSUE TITLE
Refactor: StringValue.escape

### ISSUE THREAD

**Issue by EmilGedda** [soffan20/sirix#16]
Current cyclomatic complexity: 18

**Comment by EmilGedda** [comment]
New complexity: 2

**Comment by JohannesLichtenberger** [comment]
@EmilGedda hey, of course any help is greatly appriciated :+1:

So, would be great to get your refactorings upstream :)

BTW: Do you have use cases for SirixDB? :)

**Comment by EmilGedda** [comment]
> BTW: Do you have use cases for SirixDB? :)

Not currently, these modifications are a part of a university course as you have guessed.
Will continue the conversation in sirixdb/sirix/pull/196 as I can't guarantee that this repo will exist after the course ends.
